global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#aleksey_makarov'
